name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Live
        if: github.event_name == 'push'
        run: |
          firebase deploy --only hosting:kipepeoaerospace --token "${{ secrets.FIREBASE_TOKEN }}" --project kipepeo-infrastructure

      - name: Deploy to Firebase Preview Channel
        if: github.event_name == 'pull_request'
        run: |
          firebase hosting:channel:deploy pr-${{ github.event.number }} --only hosting:kipepeoaerospace --token "${{ secrets.FIREBASE_TOKEN }}" --project kipepeo-infrastructure

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Tear Down Preview Channel
        run: |
          firebase hosting:channel:delete pr-${{ github.event.number }} --force --only hosting:kipepeoaerospace --token "${{ secrets.FIREBASE_TOKEN }}" --project kipepeo-infrastructure